"""
PDF report generation using ReportLab.

All exports share a common header (business name, report title, date range,
generated by, generated on) and footer (page numbers).

Each `write_*` helper takes a populated dataclass / list from
`app.services.report_service` plus an output path and writes the PDF.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Iterable, List, Optional, Sequence

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.core.utils import format_date, format_money
from app.services import report_service


# ---------------------------------------------------------------------------
# Style helpers
# ---------------------------------------------------------------------------

PRIMARY = colors.HexColor("#2563EB")
DARK = colors.HexColor("#0F172A")
MUTED = colors.HexColor("#64748B")
ROW_ALT = colors.HexColor("#F8FAFC")
BORDER = colors.HexColor("#E2E8F0")
SUCCESS = colors.HexColor("#16A34A")
DANGER = colors.HexColor("#DC2626")


def _styles():
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle(
            "h1", parent=base["Heading1"], fontSize=18, leading=22,
            textColor=DARK, spaceAfter=4,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontSize=13, leading=16,
            textColor=DARK, spaceBefore=12, spaceAfter=6,
        ),
        "meta": ParagraphStyle(
            "meta", parent=base["Normal"], fontSize=9, textColor=MUTED,
            leading=12,
        ),
        "small": ParagraphStyle(
            "small", parent=base["Normal"], fontSize=9, textColor=DARK,
        ),
        "kpi_label": ParagraphStyle(
            "kpi_label", fontSize=8, textColor=MUTED, leading=10,
        ),
        "kpi_value": ParagraphStyle(
            "kpi_value", fontSize=12, textColor=DARK, leading=14, fontName="Helvetica-Bold",
        ),
        "footer": ParagraphStyle(
            "footer", fontSize=8, textColor=MUTED, alignment=1,
        ),
    }


def _header(title: str, subtitle: str, generated_by: str) -> List:
    s = _styles()
    business_name = "Brenda's Printing Hub"
    return [
        Paragraph(f"<b>{business_name}</b>", s["h1"]),
        Paragraph(title, ParagraphStyle(
            "title", parent=s["h2"], fontSize=12, textColor=PRIMARY,
            spaceBefore=0, spaceAfter=2,
        )),
        Paragraph(subtitle, s["meta"]),
        Paragraph(
            f"Generated by: <b>{generated_by}</b> on "
            f"{datetime.now().strftime('%d %b %Y %H:%M')}",
            s["meta"],
        ),
        Spacer(1, 8),
    ]


def _hr_table() -> Table:
    """A 1px tall horizontal-rule rendered as a table."""
    t = Table([[""]], colWidths=[170 * mm], rowHeights=[0.5])
    t.setStyle(TableStyle([
        ("LINEABOVE", (0, 0), (-1, 0), 0.6, BORDER),
    ]))
    return t


def _data_table(headers: Sequence[str], rows: Sequence[Sequence],
                *, col_widths: Optional[Sequence] = None,
                right_align_cols: Sequence[int] = ()) -> Table:
    table_data = [list(headers), *[list(r) for r in rows]]
    table = Table(table_data, colWidths=col_widths, repeatRows=1)
    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
        ("TEXTCOLOR", (0, 0), (-1, 0), DARK),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, 0), 0.7, BORDER),
        ("LINEBELOW", (0, -1), (-1, -1), 0.7, BORDER),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_ALT]),
    ])
    for col in right_align_cols:
        style.add("ALIGN", (col, 0), (col, -1), "RIGHT")
    table.setStyle(style)
    return table


def _kpi_row(items: Sequence[tuple]) -> Table:
    """`items` is a list of (label, value) tuples."""
    s = _styles()
    cells = []
    for label, value in items:
        cells.append([
            Paragraph(label.upper(), s["kpi_label"]),
            Paragraph(value, s["kpi_value"]),
        ])
    cell_tables = []
    for cell in cells:
        t = Table([cell], colWidths=[None])
        t.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("BACKGROUND", (0, 0), (-1, -1), colors.white),
            ("BOX", (0, 0), (-1, -1), 0.6, BORDER),
        ]))
        cell_tables.append(t)
    # Wrap cells side by side
    col_widths = [170 * mm / max(1, len(cell_tables))] * len(cell_tables)
    row = Table([cell_tables], colWidths=col_widths)
    row.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return row


# ---------------------------------------------------------------------------
# Page footer with page numbers
# ---------------------------------------------------------------------------

def _on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawCentredString(
        A4[0] / 2, 12 * mm,
        f"Brenda's Printing Hub  -  Page {doc.page}",
    )
    canvas.restoreState()


def _doc(path: Path) -> SimpleDocTemplate:
    return SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Brenda's Printing Hub Report",
        author="Brenda's Printing Hub",
    )


# ---------------------------------------------------------------------------
# Daily report
# ---------------------------------------------------------------------------

def write_daily_report(report: report_service.DailyReport, path: Path,
                       *, generated_by: str = "User") -> None:
    s = _styles()
    doc = _doc(path)
    story: List = []
    story += _header(
        "Daily Business Report",
        f"For {format_date(report.report_date, '%A, %d %B %Y')}",
        generated_by,
    )
    story.append(_hr_table())
    story.append(Spacer(1, 8))

    story.append(_kpi_row([
        ("Gross Sales", format_money(report.gross_sales)),
        ("Net Profit", format_money(report.net_profit)),
        ("Expected Cash", format_money(report.expected_cash)),
    ]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Sales by category", s["h2"]))
    story.append(_data_table(
        ["Category", "Amount (UGX)"],
        [
            ["Computer Work", format_money(report.computer_sales, with_symbol=False)],
            ["Fridge / Drinks", format_money(report.fridge_sales, with_symbol=False)],
            ["Labelling", format_money(report.labelling_sales, with_symbol=False)],
            ["GROSS TOTAL", format_money(report.gross_sales, with_symbol=False)],
        ],
        col_widths=[80 * mm, 90 * mm],
        right_align_cols=[1],
    ))

    story.append(Paragraph("Sales by payment method", s["h2"]))
    story.append(_data_table(
        ["Method", "Amount (UGX)"],
        [
            ["Cash", format_money(report.cash_sales, with_symbol=False)],
            ["Mobile Money", format_money(report.mobile_money_sales, with_symbol=False)],
            ["Bank", format_money(report.bank_sales, with_symbol=False)],
        ],
        col_widths=[80 * mm, 90 * mm],
        right_align_cols=[1],
    ))

    story.append(Paragraph("Profitability & cash", s["h2"]))
    story.append(_data_table(
        ["Item", "Amount (UGX)"],
        [
            ["Gross Sales", format_money(report.gross_sales, with_symbol=False)],
            ["- Business Expenses", format_money(report.business_expenses, with_symbol=False)],
            ["= Net Business Profit", format_money(report.net_profit, with_symbol=False)],
            ["Owner Withdrawals (separate)", format_money(report.owner_withdrawals, with_symbol=False)],
            ["Expected Cash on Hand", format_money(report.expected_cash, with_symbol=False)],
        ]
        + (
            [
                ["Actual Cash Counted", format_money(report.actual_cash, with_symbol=False)],
                ["Difference", format_money(report.cash_difference, with_symbol=False)],
            ] if report.has_closing else []
        ),
        col_widths=[100 * mm, 70 * mm],
        right_align_cols=[1],
    ))

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)


# ---------------------------------------------------------------------------
# Monthly report
# ---------------------------------------------------------------------------

def write_monthly_report(report: report_service.MonthlyReport, path: Path,
                         *, generated_by: str = "User") -> None:
    s = _styles()
    doc = _doc(path)
    story: List = []
    story += _header(
        "Monthly Business Report",
        f"{report.month_label}  -  {format_date(report.start)} to {format_date(report.end)}",
        generated_by,
    )
    story.append(_hr_table())
    story.append(Spacer(1, 8))

    story.append(_kpi_row([
        ("Gross Sales", format_money(report.gross_sales)),
        ("Net Profit", format_money(report.net_profit)),
        ("Available Cash", format_money(report.available_cash)),
    ]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Sales by category", s["h2"]))
    story.append(_data_table(
        ["Category", "Amount (UGX)"],
        [
            ["Computer Work", format_money(report.computer_sales, with_symbol=False)],
            ["Fridge / Drinks", format_money(report.fridge_sales, with_symbol=False)],
            ["Labelling", format_money(report.labelling_sales, with_symbol=False)],
            ["GROSS TOTAL", format_money(report.gross_sales, with_symbol=False)],
        ],
        col_widths=[80 * mm, 90 * mm],
        right_align_cols=[1],
    ))

    story.append(Paragraph("Profitability", s["h2"]))
    story.append(_data_table(
        ["Item", "Amount (UGX)"],
        [
            ["Gross Sales", format_money(report.gross_sales, with_symbol=False)],
            ["- Business Expenses", format_money(report.business_expenses, with_symbol=False)],
            ["= Net Monthly Profit", format_money(report.net_profit, with_symbol=False)],
            ["Owner Withdrawals (separate)", format_money(report.owner_withdrawals, with_symbol=False)],
            ["Available Cash (after withdrawals)", format_money(report.available_cash, with_symbol=False)],
        ],
        col_widths=[100 * mm, 70 * mm],
        right_align_cols=[1],
    ))

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)


# ---------------------------------------------------------------------------
# Sales by category, expense, withdrawal, stock, labelling, P&L
# ---------------------------------------------------------------------------

def _range_subtitle(label: str) -> str:
    return f"Period: {label}"


def write_category_report(rows: List[report_service.CategoryReportRow],
                          period_label: str, path: Path,
                          *, generated_by: str = "User") -> None:
    doc = _doc(path)
    story: List = []
    story += _header("Sales by Category", _range_subtitle(period_label), generated_by)
    story.append(_hr_table())
    story.append(Spacer(1, 8))

    table_rows = [
        [r.category, format_money(r.total, with_symbol=False), f"{r.percentage:.1f}%"]
        for r in rows
    ]
    total = sum(r.total for r in rows)
    table_rows.append(["TOTAL", format_money(total, with_symbol=False), "100.0%"])
    story.append(_data_table(
        ["Category", "Amount (UGX)", "Share"],
        table_rows,
        col_widths=[70 * mm, 60 * mm, 40 * mm],
        right_align_cols=[1, 2],
    ))
    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)


def write_expense_report(rows: List[report_service.ExpenseReportRow],
                         period_label: str, path: Path,
                         *, generated_by: str = "User") -> None:
    doc = _doc(path)
    story: List = []
    story += _header("Expense Report", _range_subtitle(period_label), generated_by)
    story.append(_hr_table())
    story.append(Spacer(1, 8))

    table_rows = [
        [r.category, str(r.record_count),
         format_money(r.total, with_symbol=False), f"{r.percentage:.1f}%"]
        for r in rows if r.total > 0
    ]
    total = sum(r.total for r in rows)
    table_rows.append([
        "TOTAL", str(sum(r.record_count for r in rows)),
        format_money(total, with_symbol=False), "100.0%",
    ])
    story.append(_data_table(
        ["Category", "Records", "Amount (UGX)", "Share"],
        table_rows,
        col_widths=[55 * mm, 30 * mm, 50 * mm, 35 * mm],
        right_align_cols=[1, 2, 3],
    ))
    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)


def write_withdrawal_report(rows: List[report_service.WithdrawalReportRow],
                            period_label: str, path: Path,
                            *, generated_by: str = "User") -> None:
    doc = _doc(path)
    story: List = []
    story += _header("Owner Withdrawal Report", _range_subtitle(period_label), generated_by)
    story.append(_hr_table())
    story.append(Spacer(1, 8))

    table_rows = [
        [r.reason, str(r.record_count),
         format_money(r.total, with_symbol=False), f"{r.percentage:.1f}%"]
        for r in rows if r.total > 0
    ]
    total = sum(r.total for r in rows)
    table_rows.append([
        "TOTAL", str(sum(r.record_count for r in rows)),
        format_money(total, with_symbol=False), "100.0%",
    ])
    story.append(_data_table(
        ["Reason", "Records", "Amount (UGX)", "Share"],
        table_rows,
        col_widths=[55 * mm, 30 * mm, 50 * mm, 35 * mm],
        right_align_cols=[1, 2, 3],
    ))
    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)


def write_stock_report(rows: List[report_service.StockReportRow], path: Path,
                       *, generated_by: str = "User") -> None:
    doc = _doc(path)
    story: List = []
    story += _header(
        "Stock Report",
        f"Snapshot at {datetime.now().strftime('%d %b %Y %H:%M')}",
        generated_by,
    )
    story.append(_hr_table())
    story.append(Spacer(1, 8))

    table_rows = [
        [r.product_name + (f" ({r.brand})" if r.brand else ""),
         str(r.stock_in), str(r.stock_sold), str(r.remaining),
         format_money(r.buying_price, with_symbol=False),
         format_money(r.selling_price, with_symbol=False),
         format_money(r.stock_value, with_symbol=False),
         format_money(r.estimated_profit, with_symbol=False)]
        for r in rows
    ]
    total_value = sum(r.stock_value for r in rows)
    total_profit = sum(r.estimated_profit for r in rows)
    table_rows.append([
        "TOTAL", "", "", "", "", "",
        format_money(total_value, with_symbol=False),
        format_money(total_profit, with_symbol=False),
    ])
    story.append(_data_table(
        ["Product", "In", "Sold", "Remaining", "Buy", "Sell", "Value", "Est. profit"],
        table_rows,
        col_widths=[45 * mm, 12 * mm, 12 * mm, 18 * mm, 18 * mm, 18 * mm, 25 * mm, 22 * mm],
        right_align_cols=[1, 2, 3, 4, 5, 6, 7],
    ))
    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)


def write_labelling_report(rows: List[report_service.LabellingReportRow],
                           period_label: str, path: Path,
                           *, total_revenue: float = 0.0,
                           generated_by: str = "User") -> None:
    s = _styles()
    doc = _doc(path)
    story: List = []
    story += _header("Labelling Jobs Report", _range_subtitle(period_label), generated_by)
    story.append(_hr_table())
    story.append(Spacer(1, 8))

    total_count = sum(r.count for r in rows)
    total_value = sum(r.total_value for r in rows)
    total_outstanding = sum(r.outstanding for r in rows)

    story.append(_kpi_row([
        ("Total Jobs", str(total_count)),
        ("Total Value", format_money(total_value)),
        ("Outstanding", format_money(total_outstanding)),
        ("Revenue (period)", format_money(total_revenue)),
    ]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Jobs by status", s["h2"]))
    table_rows = [
        [r.status, str(r.count),
         format_money(r.total_value, with_symbol=False),
         format_money(r.outstanding, with_symbol=False)]
        for r in rows
    ]
    table_rows.append([
        "TOTAL", str(total_count),
        format_money(total_value, with_symbol=False),
        format_money(total_outstanding, with_symbol=False),
    ])
    story.append(_data_table(
        ["Status", "Count", "Total (UGX)", "Outstanding (UGX)"],
        table_rows,
        col_widths=[40 * mm, 30 * mm, 50 * mm, 50 * mm],
        right_align_cols=[1, 2, 3],
    ))
    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)


def write_profit_loss_report(report: report_service.ProfitLossReport, path: Path,
                             *, generated_by: str = "User") -> None:
    s = _styles()
    doc = _doc(path)
    story: List = []
    story += _header(
        "Profit & Loss Report",
        f"Period: {report.label}  -  "
        f"{format_date(report.start)} to {format_date(report.end)}",
        generated_by,
    )
    story.append(_hr_table())
    story.append(Spacer(1, 8))

    story.append(_kpi_row([
        ("Gross Sales", format_money(report.gross_sales)),
        ("Business Expenses", format_money(report.business_expenses)),
        ("Net Profit", format_money(report.net_profit)),
    ]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Sales by category", s["h2"]))
    sales_rows = [
        [cat, format_money(amount, with_symbol=False)]
        for cat, amount in report.sales_by_category.items()
    ]
    sales_rows.append(["GROSS SALES",
                       format_money(report.gross_sales, with_symbol=False)])
    story.append(_data_table(
        ["Category", "Amount (UGX)"],
        sales_rows,
        col_widths=[80 * mm, 90 * mm],
        right_align_cols=[1],
    ))

    if report.expenses_by_category:
        story.append(Paragraph("Business expenses", s["h2"]))
        exp_rows = [
            [cat, format_money(amount, with_symbol=False)]
            for cat, amount in report.expenses_by_category.items()
        ]
        exp_rows.append(["TOTAL EXPENSES",
                         format_money(report.business_expenses, with_symbol=False)])
        story.append(_data_table(
            ["Category", "Amount (UGX)"],
            exp_rows,
            col_widths=[80 * mm, 90 * mm],
            right_align_cols=[1],
        ))

    story.append(Paragraph("Net profit", s["h2"]))
    story.append(_data_table(
        ["Item", "Amount (UGX)"],
        [
            ["Gross Sales", format_money(report.gross_sales, with_symbol=False)],
            ["- Business Expenses", format_money(report.business_expenses, with_symbol=False)],
            ["= NET PROFIT", format_money(report.net_profit, with_symbol=False)],
        ],
        col_widths=[100 * mm, 70 * mm],
        right_align_cols=[1],
    ))

    if report.withdrawals_by_reason:
        story.append(Paragraph("Owner withdrawals (separate from profit)", s["h2"]))
        wd_rows = [
            [reason, format_money(amount, with_symbol=False)]
            for reason, amount in report.withdrawals_by_reason.items()
        ]
        wd_rows.append(["TOTAL WITHDRAWALS",
                        format_money(report.owner_withdrawals, with_symbol=False)])
        story.append(_data_table(
            ["Reason", "Amount (UGX)"],
            wd_rows,
            col_widths=[80 * mm, 90 * mm],
            right_align_cols=[1],
        ))

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
